#!/bin/bash
# Sweep for: computer2/part1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_1757.json --wandb True