#!/bin/bash
# Sweep for: computer3/gpu0/job0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job0/config_2635.json --wandb True