#!/bin/bash
# Sweep for: computer2/part3

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_2343.json --wandb True