#!/bin/bash
# Sweep for: computer1/part1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0585.json --wandb True