#!/bin/bash
# Sweep for: computer1/part0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part0/config_0292.json --wandb True