#!/bin/bash
# Sweep for: computer3/gpu1/job0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job0/config_2927.json --wandb True