#!/bin/bash
# Sweep for: computer1/part3

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_0999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_1171.json --wandb True