#!/bin/bash
# Sweep for: computer3/gpu0/job1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_2999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job1/config_3219.json --wandb True