#!/bin/bash
# Sweep for: computer1/part2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_0878.json --wandb True