#!/bin/bash
# Sweep for: computer2/part0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_1464.json --wandb True