#!/bin/bash
# Sweep for: computer3/gpu1/job1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job1/config_3511.json --wandb True