#!/bin/bash
# Sweep for: computer2/part2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_1999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_2050.json --wandb True