#!/bin/bash
# Sweep for: computer3/gpu0/job2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu0/job2/config_3803.json --wandb True