#!/bin/bash
# Sweep for: computer3/gpu1/job2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_3999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/gpu1/job2/config_4095.json --wandb True